site_name: JJUI

docs_dir: docsstorage
site_dir: docs

repo_url: http://github.com/oc-ob/JJUI
edit_uri: ""

nav:
 - Home:
   - Introduction: index.md
   - Installation: installation.md
   - API:
     - Drag bar: api/dragbar.md
     - Notification: api/notification.md
     - Radial progress: api/radialprogress.md
     - Switch: api/switch.md

 - Changelog: changelog.md
   

theme:

 name: material

 custom_dir: customdir

 # Theme
 palette:
    scheme: slate
    primary: indigo
    accent: indigo
 
 # Fonts and icon
 font:
    text: Roboto
    code: Roboto Mono

 favicon: images/logo2png.png

 icon:
  logo: logo2
  
  admonition:
   <type>: <icon>

 # Features
 features:
  - navigation.instant
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - navigation.tabs
  - content.code.annotate

extra:
 version: 1.0
 generator: false
 social:
  - icon: fontawesome/brands/github
    link: https://github.com/oc-ob
    name: oc_ob on Github

markdown_extensions:

  - admonition

  - pymdownx.details

  - pymdownx.superfences